<img src="http://imgur.com/1ZcRyrc.png" style="float: left; margin: 20px; height: 55px">

## Walkthrough of Standard EDA Procedure

_Authors: Kiefer Katovich (SF)_

---

This lesson uses a boston housing market dataset to walk through a basic exploratory data analysis procedure, starting from the very beginning with loading the data. 

Though in many if not most cases the EDA procedure will be considerably more involved, this should give you an idea of the basic workflow a data scientist would go through when taking a look at a new dataset.

Note: this lesson is strictly exploratory. We will not be formulating any hypotheses about the data or testing them. In many cases you may have formulated a hypothesis before even looking at your data, which could considerably affect your focus and choices in what to investigate.

### Lesson Guide

- [Description of the Boston Housing Data](#data_description)
- [Loading the data](#load_data)
- [Initial examination](#header)
- [Drop unwanted columns](#drop)
- [Clean corrupted data](#clean)
- [Count null values and drop rows](#drop_nulls)
- [Rename columns](#rename)
- [Investigate potential outliers with boxplots](#boxplots)
- [Plot all variables together](#plot_all)
- [Standardization of variables](#standardization)
- [Plot the standardized variables together](#plot_all_rescaled)
- [Look at the covariance or correlation between variables](#cov_cor)

<a id='data_description'></a>

### Description of the Boston Housing Data columns

---

The columns of the dataset are coded. The corresponding descriptions are:

    CRIM: per capita crime rate by town 
    ZN: proportion of residential land zoned for lots over 25,000 sq.ft. 
    INDUS: proportion of non-retail business acres per town 
    CHAS: Charles River dummy variable (= 1 if tract bounds river; 0 otherwise) 
    NOX: nitric oxides concentration (parts per 10 million) 
    RM: average number of rooms per dwelling 
    AGE: proportion of owner-occupied units built prior to 1940 
    DIS: weighted distances to five Boston employment centres 
    RAD: index of accessibility to radial highways 
    TAX: full-value property-tax rate per 10000 dollars
    PTRATIO: pupil-teacher ratio by town 
    B: 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town 
    LSTAT: % lower status of the population 
    MEDV: Median value of owner-occupied homes in 1000's of dollars
    
Each row in the dataset represents a different suburb of Boston.

These descriptions of shortened or coded variables are often called "codebooks" or data dictionaries. They are typically found with datasets you might find online in a separate file.

**Load packages:**

In [1]:
import numpy as np
import scipy.stats as stats
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

sns.set_style('darkgrid')

%config InlineBackend.figure_format = 'retina'
%matplotlib inline

<a id='load_data'></a>

### 1. Load the data

---

Import the csv into a pandas DataFrame.

In [2]:
boston_file = pd.read_csv('/Users/Mahendra/desktop/GA/hw/3.2.1_eda-basic_eda_walkthrough-lesson/datasets/housing.csv')

In [3]:
# A:
boston_file

,Unnamed: 0,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,1,0.00632,18.0,2.31,0,0.538,6.575,65.2,"4,09",1,296,15.3,396.90,4.98,24.0
1,2,0.02731,0.0,7.07,0,0.469,6.421,78.9,"4,9671",2,242,17.8,396.90,9.14,21.6
2,3,0.02729,0.0,7.07,0,0.469,7.185,61.1,"4,9671",2,242,17.8,392.83,4.03,34.7
3,4,0.03237,0.0,2.18,0,0.458,6.998,45.8,"6,0622",3,222,18.7,394.63,2.94,33.4
4,5,0.06905,0.0,2.18,0,0.458,7.147,54.2,"6,0622",3,222,18.7,396.90,5.33,36.2
5,6,0.02985,0.0,2.18,0,0.458,6.430,58.7,"6,0622",3,222,18.7,394.12,5.21,28.7
6,7,0.08829,12.5,7.87,0,0.524,6.012,66.6,"5,5605",5,311,15.2,395.60,12.43,22.9
7,8,0.14455,12.5,7.87,0,0.524,6.172,96.1,"5,9505",5,311,15.2,396.90,19.15,27.1
8,9,0.21124,12.5,7.87,0,0.524,5.631,100.0,"6,0821",5,311,15.2,386.63,29.93,16.5
9,10,0.17004,12.5,7.87,0,0.524,6.004,85.9,"6,5921",5,311,15.2,386.71,17.10,18.9
10,11,0.22489,12.5,7.87,0,0.524,6.377,94.3,"6,3467",5,311,15.2,392.52,20.45,15.0
11,12,0.11747,12.5,7.87,0,0.524,6.009,82.9,"6,2267",5,311,15.2,396.90,13.27,18.9
12,13,0.09378,12.5,7.87,0,0.524,5.889,39.0,"5,4509",5,311,15.2,390.50,15.71,21.7
13,14,0.62976,0.0,8.14,0,0.538,5.949,61.8,"4,7075",4,307,21.0,396.90,8.26,20.4
14,15,0.63796,0.0,8.14,0,0.538,6.096,84.5,"4,4619",4,307,21.0,380.02,10.26,18.2
15,16,0.62739,0.0,8.14,0,0.538,5.834,56.5,"4,4986",4,307,21.0,395.62,8.47,19.9
16,17,1.05393,0.0,8.14,0,0.538,5.935,29.3,"4,4986",?,307,21.0,386.85,6.58,23.1
17,18,0.78420,0.0,8.14,0,0.538,5.990,81.7,"4,2579",4,307,21.0,386.75,14.67,17.5
18,19,0.80271,0.0,8.14,0,0.538,5.456,36.6,"3,7965",4,307,21.0,288.99,11.69,20.2
19,20,0.72580,0.0,8.14,0,0.538,5.727,69.5,"3,7965",4,307,21.0,390.95,11.28,18.2
20,21,1.25179,0.0,8.14,0,0.538,5.570,98.1,"3,7979",4,307,21.0,376.57,21.02,13.6
21,22,0.85204,0.0,8.14,0,0.538,5.965,89.2,"4,0123",?,307,21.0,392.53,13.83,19.6
22,23,1.23247,0.0,8.14,0,0.538,6.142,91.7,"3,9769",4,307,21.0,396.90,18.72,15.2
23,24,0.98843,0.0,8.14,0,0.538,5.813,100.0,"4,0952",4,307,21.0,394.54,19.88,14.5
24,25,0.75026,0.0,8.14,0,0.538,5.924,94.1,"4,3996",4,307,21.0,394.33,16.30,15.6
25,26,0.84054,0.0,8.14,0,0.538,5.599,85.7,"4,4546",4,307,21.0,303.42,16.51,13.9
26,27,0.67191,0.0,8.14,0,0.538,5.813,90.3,"4,682",4,307,21.0,376.88,14.81,16.6
27,28,0.95577,0.0,8.14,0,0.538,6.047,88.8,"4,4534",4,307,21.0,306.38,17.28,14.8
28,29,0.77299,0.0,8.14,0,0.538,6.495,94.4,"4,4547",4,307,21.0,387.94,12.80,18.4
29,30,1.00245,0.0,8.14,0,0.538,6.674,87.3,"4,239",4,307,21.0,380.23,11.98,21.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
476,477,4.87141,0.0,18.10,0,0.614,6.484,93.6,"2,3053",24,666,20.2,396.21,18.68,16.7
477,478,15.02340,0.0,18.10,0,0.614,5.304,97.3,"2,1007",24,666,20.2,349.48,24.91,12.0
478,479,10.23300,0.0,18.10,0,0.614,6.185,96.7,"2,1705",24,666,20.2,379.70,18.03,14.6
479,480,14.33370,0.0,18.10,0,0.614,6.229,88.0,"1,9512",24,666,20.2,383.32,13.11,21.4
480,481,5.82401,0.0,18.10,0,0.532,6.242,64.7,"3,4242",24,666,20.2,396.90,10.74,23.0
481,482,5.70818,0.0,18.10,0,0.532,6.750,74.9,"3,3317",24,666,20.2,393.07,7.74,23.7
482,483,5.73116,0.0,18.10,0,0.532,7.061,77.0,"3,4106",24,666,20.2,395.28,7.01,25.0
483,484,2.81838,0.0,18.10,0,0.532,5.762,40.3,"4,0983",24,666,20.2,392.92,10.42,21.8
484,485,2.37857,0.0,18.10,0,0.583,5.871,41.9,"3,724",24,666,20.2,370.73,13.34,20.6
485,486,3.67367,0.0,18.10,0,0.583,6.312,51.9,"3,9917",24,666,20.2,388.62,10.58,21.2
486,487,5.69175,0.0,18.10,0,0.583,6.114,79.8,"3,5459",24,666,20.2,392.68,14.98,19.1
487,488,4.83567,0.0,18.10,0,0.583,5.905,53.2,"3,1523",24,666,20.2,388.22,11.45,20.6
488,489,0.15086,0.0,27.74,0,0.609,5.454,92.7,"1,8209",4,711,20.1,395.09,18.06,15.2
489,490,0.18337,0.0,27.74,0,0.609,5.414,98.3,"1,7554",4,711,20.1,344.05,23.97,7.0
490,491,0.20746,0.0,27.74,0,0.609,5.093,98.0,"1,8226",4,711,20.1,318.43,29.68,8.1
491,492,0.10574,0.0,27.74,0,0.609,5.983,98.8,"1,8681",4,711,20.1,390.11,18.07,13.6
492,493,0.11132,0.0,27.74,0,0.609,5.983,83.5,"2,1099",4,711,20.1,396.90,13.35,20.1
493,494,0.17331,0.0,9.69,0,0.585,5.707,54.0,"2,3817",6,391,19.2,396.90,12.01,21.8
494,495,0.27957,0.0,9.69,0,0.585,5.926,42.6,"2,3817",6,391,19.2,396.90,13.59,24.5
495,496,0.17899,0.0,9.69,0,0.585,5.670,28.8,"2,7986",6,391,19.2,393.29,17.60,23.1
496,497,0.28960,0.0,9.69,0,0.585,5.390,72.9,"2,7986",6,391,19.2,396.90,21.14,19.7
497,498,0.26838,0.0,9.69,0,0.585,5.794,70.6,"2,8927",6,391,19.2,396.90,14.10,18.3
498,499,0.23912,0.0,9.69,0,0.585,6.019,65.3,"2,4091",6,391,19.2,396.90,12.92,21.2
499,500,0.17783,0.0,9.69,0,0.585,5.569,73.5,"2,3999",?,391,19.2,395.77,15.10,17.5
500,501,0.22438,0.0,9.69,0,0.585,6.027,79.7,"2,4982",6,391,19.2,396.90,14.33,16.8
501,502,0.06263,0.0,11.93,0,0.573,6.593,69.1,"2,4786",?,273,21.0,391.99,9.67,22.4
502,503,0.04527,0.0,11.93,0,0.573,6.120,76.7,"2,2875",1,273,21.0,396.90,9.08,20.6
503,504,0.06076,0.0,11.93,0,0.573,6.976,91.0,"2,1675",1,273,21.0,396.90,5.64,23.9
504,505,0.10959,0.0,11.93,0,0.573,6.794,89.3,"2,3889",1,273,21.0,393.45,6.48,22.0
505,506,0.04741,0.0,11.93,0,0.573,6.030,80.8,"2,505",1,273,21.0,396.90,7.88,11.9

<a id='header'></a>

### 2. Describe the basic format of the data and the columns

---

Use the `.head()` function (and optionally pass in an integer for the number of rows you want to see) to examine what the loaded data looks like. This is a good initial step to get a feel for what is in the csv and what problems may be present.

The `.dtypes` attribute tells you the data type for each of your columns.

In [4]:
# Print out the first 8 rows:

In [5]:
# Look at the dtypes of the columns:

<a id='drop'></a>

### 2. Drop unwanted columns

---

There is a column labeled `Unnamed: 0` which appears to simply number the rows. We already have the number id of the rows in the DataFrame's index and so we don't need this column.

The `.drop()` built-in function can be used to get rid of a column. When removing a column, we need to specify `axis=1` to the function.

For the record, the `.index` attribute holds the row indices. This is the the sister attribute to the `.columns` attribute that we work with more often.

In [6]:
# print out the index object and the first 20 items in the DataFrame's index 
# to see that we have these row numbers already:

In [7]:
# Remove the unneccesary column:

<a id='clean'></a>

### 3. Clean corrupted columns

---

You may have noticed when we examined the `dtypes` attribute that two of the columns were of type "object", indicating that they were string. However, we know from the data description above (and we can infer from the header of the data) that `DIS` and `RAD` should in fact be numeric.

It is pretty common to have numeric columns represented as strings in your data if some of the observations are corrupted. It is important to always check the data types of your columns.

**3.A What is causing the `DIS` column to be encoded as a string? Figure out a way to make sure the column is numeric while preserving information.**

*Tip: The `.map()` built-in function on a column will apply a function to each element of the column.*

In [8]:
# A:

**3.B What is causing the `RAD` column to be encoded as string? Figure out a way to make sure the column is numeric while preserving information.**

*Tip: You can put `np.nan` values in place of corrupted observations, which are numeric "Null" values.*

In [9]:
# A:

<a id='drop_nulls'></a>

### 4. Determine how many observations are missing

---

Having replaced the question marks with `np.nan` values, we know that there are some missing observations for the `RAD` column. 

When we start to build models with data, null values in observations are (almost) never allowed. It is important to always see how many observations are missing and for which columns.

A handy way to look at how many null values there are per column with pandas is:

```python
boston.isnull().sum()
```

The `.isull()` built-in function will convert the columns to boolean `True` and `False` values (returning a new dataframe) where null values are indicated by `True`. 

The `.sum()` function tacked on to the back of that will then sum these boolean columns, and the total number of null values per column will be returned.

In [10]:
# A:

**Drop the null values.** 

In this case, lets keep it simple and just drop the rows from the dataset that contain null values. If a column has a ton of null values it often makes more sense to drop the column entirely instead of the rows with null values. In this case, we will just drop the rows.

The `.dropna()` function will drop any rows that have null values for you.

In [11]:
# A:

<a id='rename'></a>

### 5. Make the column names more descriptive

---

Often it is annoying to have to memorize what the codes mean for columns, or reference the codebook whenever I want to know the meaning of a variable. It often makes sense to rename columns that are not descriptive.

There is more than one way to do this, but one easy way is to use the `.rename()` function.

Here are the column names and their descriptions again for reference:

    CRIM: per capita crime rate by town 
    ZN: proportion of residential land zoned for lots over 25,000 sq.ft. 
    INDUS: proportion of non-retail business acres per town 
    CHAS: Charles River dummy variable (= 1 if tract bounds river; 0 otherwise) 
    NOX: nitric oxides concentration (parts per 10 million) 
    RM: average number of rooms per dwelling 
    AGE: proportion of owner-occupied units built prior to 1940 
    DIS: weighted distances to five Boston employment centres 
    RAD: index of accessibility to radial highways 
    TAX: full-value property-tax rate per 10000 dollars
    PTRATIO: pupil-teacher ratio by town 
    B: 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town 
    LSTAT: % lower status of the population 
    MEDV: Median value of owner-occupied homes in 1000's of dollars

In [12]:
# A:

<a id='describe'></a>

### 6. Describe the summary statistics for the columns

---

The `.describe()` function gives summary statistics for each of your variables. What are some, if any, oddities you notice about the variables based on this output?

In [13]:
# A:

<a id='boxplots'></a>

### 7. Plot variables with potential outliers using boxplots.

---

Here we will use the seaborn package to plot boxplots of the variables we have identified as potentially having outliers.

Some notes on seaborn's boxplot keyword argument options:

    orient: can be 'v' or 'h' for vertical and horizontal, respectively
    fliersize: the size of the outlier points (pixels I think)
    linewidth: the width of line outlining the boxplot
    notch: show the confidence interval for the median (calculated by seaborn/plt.boxplot)
    saturation: saturate the colors to an extent

There are more keyword arguments available but those are most relevant for now.

In [14]:
# rate of crime

In [15]:
# percent owner occupied

In [16]:
# business zone percent

In [17]:
# black population statistic

<a id='plot_all'></a>

### 8. Plot all the variables on boxplots together.

---

Plot all the variables using using a horizontal boxplot with seaborn. What is wrong with this plot, if anything?

In [18]:
# A:


<a id='standardization'></a>

### 9. Standardizing variables

---

Rescaling variables is very common, and sometimes essential. For example, when we get to regularization of models the rescaling procedure becomes a requirement before fitting the model.

Here we'll rescale the variables using a procedure called "standardization", which forces the distribution of each variable to have a mean of 0 and a standard deviation of 1.

Standardization is not complicated:

    standardized_variable = (variable - mean_of_variable) / std_dev_of_variable
    
Note: Nothing else is changed about the distribution of the variable. It doesn't become normally distributed.

**9.A Pull out rate of crime and plot the distribution.**

Also print out the mean and standard deviation of the original variable.

In [19]:
# A:

**9.B Standardize the rate_of_crime variable. Notice the new mean is centered at 0.**

In [20]:
# A:

**9.C Plot the original and standardized rate of crime. Notice that nothing changes about the distribution except for the location and the scale.**

In [21]:
# A:


<a id='plot_all_rescaled'></a>

### 10. Standardize all of the columns and re-create the boxplot

---

Pandas DataFrames make it extremely easy to standardize the columns all at once. You can standardize the data like so:

```python
boston_norm = (boston - boston.mean()) / boston.std()
```

Create a standardized version of the data and recreate the boxplot. Now you can better examine the differences in the shape of distributions across our variables.

In [22]:
# A:


<a id='cov_cor'></a>

### 11. Covariance and correlation matrices

---

A great way to easily get a feel for linear relationships between your variables is with a correlation matrix.

Below is the formula for the covariance between two variables $X$ and $Y$:

#### 11.A Covariance

Given sample size $N$ variables $X$ and $Y$, with means $\bar{X}$ and $\bar{Y}$:

### $$ \text{covariance}(X, Y) = \sum_{i=1}^N \frac{(X - \bar{X})(Y - \bar{Y})}{N}$$

The covariance is a measure of "relatedness" between variables. It is literally the sum of deviations from the mean of $X$ times deviations from the mean of $Y$ adjusted by the sample size $N$.

Code the covariance between `pct_underclass` and `home_median_value` below by hand. Verify that you got the correct result using `np.cov()`. Set the keyword argument `bias=True` in `np.cov()` to have it use the same covariance calculation.

Note: `np.cov` returns a covariance _matrix_, which will be each values covariance with itself and the other variable in matrix format.

In [23]:
# A:

#### 11.B Correlation

Covariance is not very interpretable. The values are difficult to read because they are relative to the variance of the variables.

A much more common metric, and one directly calculable from the covariance, is the correlation.

Again, let $X$ and $Y$ be our two variables, with covariance $cov(X, Y)$ that we calculated above:

### $$ \text{pearson correlation}\;r = cor(X, Y) =\frac{cov(X, Y)}{std(X)std(Y)}$$

Calculate the correlation between `pct_under` and `med_value` by hand below. Check that it is the same as `np.corrcoef()` with `bias=True`:

In [24]:
# A:

#### 11.C The correlation matrix

We can see the correlation between all the numeric variables in our dataset by using pandas DataFrame's built in `.corr()` function. Use it below on the boston dataset.

It is very useful to get a feel for what is related and what is not, which can help you decide what is worth investigating further (though with a lot of variables, the matrix can be a bit overwhelming...)

In [25]:
# A: